package com.qa.exer;

import com.qa.exeception.CustomException;

public class Calculator {

	public static int calcAdd(int num1, int num2) {
		int result = num1 + num2;
		return result;
	}

	public static int calcMinus(int num1, int num2) {
		int result = num1 - num2;
		return result;
	}

	public static int calcMulti(int num1, int num2) {
		int result = num1 * num2;
		return result;
	}

	public static int calcDiv(int num1, int num2) throws CustomException {
		int result = 0;
		try {
			result = num1 / num2;
			if (num1 < num2) {
				throw new CustomException("Please ensure the first number is greater than the second!");
			}
		}

//		try {
//			return num1 / num2;
//		}
		catch (ArithmeticException e) {
			e.printStackTrace();
			System.out.println("Please don't Divide by Zero");
		} catch (CustomException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
		return result;

	}

	public static double calcpwr(double num1, double num2) {
		double result = Math.pow(num1, num2);
		return result;
	}
}
